[package]
name = "distributed-file-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1", features = ["full"] }
bcrypt = "0.15.1"
serde = { version = "1", features = ["derive"] }
jsonwebtoken = "9.3.0"
clap = "4.0"
dotenv = "0.15"