name: Docker Build and Push
on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tanboyuan/distributed-file-storage
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push Node1
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-node1
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            PROMETHEUS_PORT=9898
            GRPC_ADDR=0.0.0.0:50051
            LIBP2P_LISTEN_ADDRESS=/ip4/0.0.0.0/tcp/9000
            NODE_ADDRESS=/ip4/127.0.0.1/tcp/9000
          
      - name: Build and push Node2
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-node2
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            PROMETHEUS_PORT=9899
            GRPC_ADDR=0.0.0.0:50052
            LIBP2P_LISTEN_ADDRESS=/ip4/0.0.0.0/tcp/9001
            NODE_ADDRESS=/ip4/127.0.0.1/tcp/9001
          
      - name: Build and push Node3
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-node3
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            PROMETHEUS_PORT=9900
            GRPC_ADDR=0.0.0.0:50053
            LIBP2P_LISTEN_ADDRESS=/ip4/0.0.0.0/tcp/9002
            NODE_ADDRESS=/ip4/127.0.0.1/tcp/9002
      
      # Temp fix for cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
